# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Caleb Geniesse
tagline:          'Caleb Geniesse'
description:      'Machine Learning Scientist'


url:              /
baseurl:          https://calebgeniesse.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
gscholar:
   url:           https://scholar.google.com/citations?user=S5lu_LAAAAAJ&hl=en
linkedin:
   url:           https://www.linkedin.com/in/calebgeniesse
twitter:
  user:           https://twitter.com/calebgeniesse
github:
  repo:           https://github.com/calebgeniesse
