# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            calebgeniesse
tagline:          'Caleb Geniesse'
description:      'graduate student in biophysics <a href="https://github.com/Stanford" target="_blank">@stanford</a> <a href="https://github.com/braindynamicslab" target="_blank">@braindynamicslab</a>'
url:              https://calebgeniesse.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           https://github.com/calebgeniesse
